    # Обновляем все пакеты с помощью модуля apt
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    # Обновляем все пакеты
    - name: Upgrade all packages on servers
      apt:
        upgrade: dist
        force_apt_get: yes

    # Установка архиватора
    - name: Install archiver ark
      apt:
        name:
        - ark
        state: present
        update_cache: yes
