    # Обновляем все пакеты с помощью модуля apt
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    # Обновляем все пакеты
    - name: Upgrade all packages on servers
      apt:
        upgrade: dist
        force_apt_get: yes

    # Установка почтового клиента thunderbird
    - name: Install thunderbird email client Debian
      apt:
        name:
        - thunderbird
        - thunderbird-l10n-ru
        state: present
        update_cache: yes
	when: ansible_distribution == "Debian"

    # Установка почтового клиента thunderbird
    - name: Install thunderbird email client Ubuntu
      apt:
        name:
        - thunderbird
        - thunderbird-locale-ru
        state: present
        update_cache: yes
	when: ansible_distribution == "Ubuntu"