    # Обновляем все пакеты с помощью модуля apt
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    # Обновляем все пакеты
    - name: Upgrade all packages on servers
      apt:
        upgrade: dist
        force_apt_get: yes

    # Установка окружения рабочего стола xfce
    - name: Install desktop environment system
      apt:
        name:
          - xfce4
          - xfce4-clipman-plugin
          - xfce4-cpugraph-plugin
          - xfce4-netload-plugin
          - xfce4-taskmanager
          - xfce4-terminal
          - xfce4-xkb-plugin
          - dbus-x11
          - language-pack-ru
          - whois
        state: present
        update_cache: yes