    # Обновляем все пакеты с помощью модуля apt
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    # Обновляем все пакеты
    - name: Upgrade all packages on servers
      apt:
        upgrade: dist
        force_apt_get: yes

    # Установка пакета для работы с RDP соединением
    - name: Install xrdp service
      apt:
        name: xrdp
        state: present
        update_cache: yes
      notyfy:
        - stop xrdp
